use clap::{Arg, ArgAction, Command, value_parser};

fn repository_args(command: Command) -> Command {
    command
        .arg(Arg::new("key").short('k').long("key").value_name("KEY"))
        .arg(
            Arg::new("storage")
                .short('s')
                .long("storage")
                .value_name("STORAGE"),
        )
        .arg(
            Arg::new("password")
                .short('p')
                .long("password")
                .value_name("PASSWORD"),
        )
}

fn backup_tuning_args(command: Command) -> Command {
    command
        .arg(
            Arg::new("compress")
                .short('c')
                .long("compress")
                .value_name("LEVEL"),
        )
        .arg(
            Arg::new("chunk-size")
                .short('z')
                .long("chunk-size")
                .value_name("BYTES"),
        )
        .arg(
            Arg::new("ignore")
                .short('i')
                .long("ignore")
                .value_name("NAME")
                .action(ArgAction::Append),
        )
        .arg(
            Arg::new("no-ignore-git")
                .long("no-ignore-git")
                .action(ArgAction::SetTrue),
        )
        .arg(Arg::new("concurrency").long("concurrency").value_name("N"))
}

pub fn command() -> Command {
    let backup = backup_tuning_args(repository_args(
        Command::new("backup")
            .about("Create a backup of a directory and store it in a storage")
            .arg(
                Arg::new("message")
                    .short('m')
                    .long("message")
                    .value_name("MESSAGE"),
            )
            .arg(
                Arg::new("root-path")
                    .short('r')
                    .long("root-path")
                    .value_name("PATH"),
            )
            .arg(Arg::new("continue").long("continue").value_name("BACKUP"))
            .arg(
                Arg::new("parent")
                    .long("parent")
                    .value_name("BACKUP")
                    .num_args(0..=1),
            ),
    ))
    .subcommand(repository_args(
        Command::new("pending").about("List pending backups"),
    ))
    .subcommand(repository_args(
        Command::new("delete")
            .about("Delete a backup and its orphaned chunks")
            .arg(
                Arg::new("backup")
                    .short('b')
                    .long("backup")
                    .value_name("BACKUP"),
            ),
    ));

    let live = backup_tuning_args(repository_args(
        Command::new("live")
            .about("Keep a directory backed up and synchronized")
            .arg(
                Arg::new("message")
                    .short('m')
                    .long("message")
                    .value_name("MESSAGE"),
            )
            .arg(
                Arg::new("root-path")
                    .short('r')
                    .long("root-path")
                    .value_name("PATH"),
            )
            .arg(
                Arg::new("conflict")
                    .long("conflict")
                    .value_name("POLICY")
                    .value_parser(["local", "remote"]),
            ),
    ))
    .arg(Arg::new("continue").long("continue").value_name("BACKUP"))
    .arg(
        Arg::new("parent")
            .long("parent")
            .value_name("BACKUP")
            .num_args(0..=1),
    );

    let explore = repository_args(
        Command::new("explore")
            .about("Browse and restore files from the historical catalog")
            .arg(Arg::new("path").long("path").value_name("PATH"))
            .arg(
                Arg::new("scope")
                    .long("scope")
                    .value_name("SCOPE")
                    .value_parser(["current", "all-history"])
                    .default_value("all-history"),
            )
            .arg(Arg::new("query").long("query").value_name("QUERY"))
            .arg(
                Arg::new("history")
                    .long("history")
                    .action(ArgAction::SetTrue),
            )
            .arg(
                Arg::new("restore")
                    .long("restore")
                    .action(ArgAction::SetTrue),
            )
            .arg(
                Arg::new("select")
                    .long("select")
                    .value_name("PATH")
                    .action(ArgAction::Append),
            )
            .arg(
                Arg::new("revision")
                    .long("revision")
                    .value_name("PATH=BACKUP")
                    .action(ArgAction::Append),
            )
            .arg(
                Arg::new("target-path")
                    .short('t')
                    .long("target-path")
                    .value_name("PATH"),
            )
            .arg(Arg::new("cursor").long("cursor").value_name("CURSOR"))
            .arg(
                Arg::new("limit")
                    .long("limit")
                    .value_name("N")
                    .value_parser(value_parser!(usize))
                    .default_value("100"),
            )
            .arg(
                Arg::new("sort")
                    .long("sort")
                    .value_name("ORDER")
                    .value_parser(["name", "size", "status", "recent"])
                    .default_value("name"),
            ),
    );

    let autostart = Command::new("autostart")
        .about("Manage per-user live jobs")
        .subcommand(
            Command::new("add")
                .arg(Arg::new("name").long("name").value_name("NAME"))
                .arg(
                    Arg::new("root-path")
                        .short('r')
                        .long("root-path")
                        .value_name("PATH"),
                )
                .arg(Arg::new("key").short('k').long("key").value_name("KEY"))
                .arg(
                    Arg::new("storage")
                        .short('s')
                        .long("storage")
                        .value_name("STORAGE"),
                )
                .arg(
                    Arg::new("password")
                        .short('p')
                        .long("password")
                        .value_name("PASSWORD"),
                )
                .arg(
                    Arg::new("message")
                        .short('m')
                        .long("message")
                        .value_name("MESSAGE"),
                )
                .arg(
                    Arg::new("compress")
                        .short('c')
                        .long("compress")
                        .value_name("LEVEL"),
                )
                .arg(
                    Arg::new("chunk-size")
                        .short('z')
                        .long("chunk-size")
                        .value_name("BYTES"),
                )
                .arg(
                    Arg::new("ignore")
                        .short('i')
                        .long("ignore")
                        .value_name("NAME")
                        .action(ArgAction::Append),
                )
                .arg(
                    Arg::new("no-ignore-git")
                        .long("no-ignore-git")
                        .action(ArgAction::SetTrue),
                )
                .arg(Arg::new("concurrency").long("concurrency").value_name("N"))
                .arg(
                    Arg::new("conflict")
                        .long("conflict")
                        .value_parser(["local", "remote"]),
                )
                .arg(
                    Arg::new("start-now")
                        .long("start-now")
                        .hide(true)
                        .action(ArgAction::SetTrue),
                )
                .arg(
                    Arg::new("no-start")
                        .long("no-start")
                        .visible_alias("not-start")
                        .conflicts_with("start-now")
                        .action(ArgAction::SetTrue),
                )
                .arg(
                    Arg::new("replace")
                        .long("replace")
                        .action(ArgAction::SetTrue),
                ),
        )
        .subcommand(
            Command::new("update")
                .arg(Arg::new("name").value_name("NAME").required(true))
                .arg(
                    Arg::new("root-path")
                        .short('r')
                        .long("root-path")
                        .value_name("PATH"),
                )
                .arg(Arg::new("key").short('k').long("key").value_name("KEY"))
                .arg(
                    Arg::new("storage")
                        .short('s')
                        .long("storage")
                        .value_name("STORAGE"),
                )
                .arg(
                    Arg::new("password")
                        .short('p')
                        .long("password")
                        .value_name("PASSWORD"),
                )
                .arg(
                    Arg::new("message")
                        .short('m')
                        .long("message")
                        .value_name("MESSAGE"),
                )
                .arg(
                    Arg::new("compress")
                        .short('c')
                        .long("compress")
                        .value_name("LEVEL"),
                )
                .arg(
                    Arg::new("chunk-size")
                        .short('z')
                        .long("chunk-size")
                        .value_name("BYTES"),
                )
                .arg(
                    Arg::new("ignore")
                        .short('i')
                        .long("ignore")
                        .value_name("NAME")
                        .action(ArgAction::Append),
                )
                .arg(
                    Arg::new("no-ignore-git")
                        .long("no-ignore-git")
                        .action(ArgAction::SetTrue),
                )
                .arg(Arg::new("concurrency").long("concurrency").value_name("N"))
                .arg(
                    Arg::new("conflict")
                        .long("conflict")
                        .value_parser(["local", "remote"]),
                )
                .arg(
                    Arg::new("start-now")
                        .long("start-now")
                        .action(ArgAction::SetTrue),
                )
                .arg(
                    Arg::new("no-start")
                        .long("no-start")
                        .visible_alias("not-start")
                        .conflicts_with("start-now")
                        .action(ArgAction::SetTrue),
                ),
        )
        .subcommand(Command::new("list"))
        .subcommand(Command::new("status").arg(Arg::new("name").value_name("NAME")))
        .subcommand(Command::new("enable").arg(Arg::new("name").value_name("NAME").required(true)))
        .subcommand(Command::new("disable").arg(Arg::new("name").value_name("NAME").required(true)))
        .subcommand(
            Command::new("remove")
                .arg(Arg::new("name").value_name("NAME").required(true))
                .arg(
                    Arg::new("yes")
                        .short('y')
                        .long("yes")
                        .action(ArgAction::SetTrue),
                ),
        )
        .subcommand(
            Command::new("logs")
                .visible_alias("log")
                .arg(Arg::new("name").value_name("NAME").required(true)),
        )
        .subcommand(
            Command::new("run")
                .hide(true)
                .arg(Arg::new("job-id").value_name("JOB_ID").required(true)),
        );

    Command::new("gib")
        .about("⚡ Back up your files. Keep them in sync. Travel through their history.")
        .version(gib::VERSION)
        .subcommand_required(true)
        .arg_required_else_help(true)
        .allow_external_subcommands(true)
        .arg(
            Arg::new("mode")
                .long("mode")
                .value_name("MODE")
                .value_parser(["interactive", "json"])
                .default_value("interactive")
                .global(true),
        )
        .arg(
            Arg::new("config")
                .long("config")
                .value_name("PATH")
                .global(true),
        )
        .arg(
            Arg::new("data-dir")
                .long("data-dir")
                .value_name("PATH")
                .global(true),
        )
        .arg(
            Arg::new("no-config")
                .long("no-config")
                .action(ArgAction::SetTrue)
                .conflicts_with("config")
                .global(true),
        )
        .subcommand(
            Command::new("config").arg(
                Arg::new("author")
                    .short('a')
                    .long("author")
                    .value_name("AUTHOR"),
            ),
        )
        .subcommand(Command::new("whoami"))
        .subcommand(
            Command::new("setup").arg(
                Arg::new("no-recursive")
                    .long("no-recursive")
                    .action(ArgAction::SetTrue),
            ),
        )
        .subcommand(repository_args(Command::new("encrypt")))
        .subcommand(repository_args(Command::new("log")))
        .subcommand(repository_args(
            Command::new("search")
                .arg(Arg::new("query").value_name("QUERY").required(true))
                .arg(Arg::new("path").long("path").value_name("PREFIX"))
                .arg(Arg::new("extension").long("extension").value_name("EXT"))
                .arg(
                    Arg::new("limit")
                        .long("limit")
                        .value_parser(value_parser!(usize))
                        .default_value("100"),
                ),
        ))
        .subcommand(explore)
        .subcommand(backup)
        .subcommand(live)
        .subcommand(autostart)
        .subcommand(repository_args(
            Command::new("restore")
                .arg(
                    Arg::new("backup")
                        .short('b')
                        .long("backup")
                        .value_name("BACKUP"),
                )
                .arg(
                    Arg::new("only")
                        .long("only")
                        .value_name("PATH")
                        .num_args(0..=1)
                        .action(ArgAction::Append),
                )
                .arg(
                    Arg::new("target-path")
                        .short('t')
                        .long("target-path")
                        .value_name("PATH"),
                )
                .arg(
                    Arg::new("prune-local")
                        .short('d')
                        .long("prune-local")
                        .visible_alias("delete")
                        .action(ArgAction::SetTrue),
                ),
        ))
        .subcommand(
            Command::new("storage")
                .subcommand(
                    Command::new("add")
                        .arg(Arg::new("name").short('n').long("name").value_name("NAME"))
                        .arg(
                            Arg::new("type")
                                .short('t')
                                .long("type")
                                .value_parser(["local", "s3", "webdav"]),
                        )
                        .arg(Arg::new("path").short('p').long("path").value_name("PATH"))
                        .arg(
                            Arg::new("region")
                                .short('r')
                                .long("region")
                                .value_name("REGION"),
                        )
                        .arg(
                            Arg::new("bucket")
                                .short('b')
                                .long("bucket")
                                .value_name("BUCKET"),
                        )
                        .arg(
                            Arg::new("access-key")
                                .short('a')
                                .long("access-key")
                                .value_name("ACCESS_KEY"),
                        )
                        .arg(
                            Arg::new("secret-key")
                                .short('s')
                                .long("secret-key")
                                .value_name("SECRET_KEY"),
                        )
                        .arg(
                            Arg::new("endpoint")
                                .short('e')
                                .long("endpoint")
                                .value_name("ENDPOINT"),
                        )
                        .arg(Arg::new("url").long("url").value_name("URL"))
                        .arg(Arg::new("username").long("username").value_name("USERNAME"))
                        .arg(Arg::new("password").long("password").value_name("PASSWORD")),
                )
                .subcommand(Command::new("list"))
                .subcommand(
                    Command::new("remove")
                        .arg(Arg::new("name").short('n').long("name").value_name("NAME")),
                )
                .subcommand(repository_args(
                    Command::new("prune").arg(
                        Arg::new("yes")
                            .short('y')
                            .long("yes")
                            .action(ArgAction::SetTrue),
                    ),
                )),
        )
}
